### ISSUE TITLE
Add-Type: Could not load file or assembly

### ISSUE THREAD

**Issue by cajunitalian** [mgr32/PsISEProjectExplorer#44] opened 2015-03-23 12:40 UTC
This result is happening when I load into ISE:

Add-Type : Could not load file or assembly 'file://\\Appro-file01.us.crifnet.com\home\cl650matdart\My Documents\WindowsPowerShell\Modules\PsISEProjectExplorer\PsISEProjectExplorer.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At \\Appro-file01.us.crifnet.com\home\cl650matdart\My Documents\WindowsPowerShell\Modules\PsISEProjectExplorer\PsISEProjectExplorer.psm1:2 char:2
+     Add-Type -Path (Join-Path $PSScriptRoot 'PsISEProjectExplorer.dll')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
 
Unable to find type [PsISEProjectExplorer.ProjectExplorerWindow]: make sure that the assembly containing this type is loaded.
At \\Appro-file01.us.crifnet.com\home\cl650matdart\My Documents\WindowsPowerShell\Modules\PsISEProjectExplorer\PsISEProjectExplorer.psm1:9 char:2
+     $psISE.CurrentPowerShellTab.VerticalAddOnTools.Add($addOnName, [PsISEProjectExp ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PsISEProjectExp...tExplorerWindow:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by mgr32** [comment] 2015-03-23 13:22
Looks like your user profile directory is on an UNC path, I'll try to test and fix this path later.

In the meantime, you can try either to copy the zip contents to a local folder and run 'Import-Module c:\pathToTheLocalFolder\PsISEProjectExplorer.psm1', or follow the steps described in the following SO post: http://stackoverflow.com/questions/19957161/add-type-load-assembly-from-network-unc-share-error-0x80131515

**Comment by cajunitalian** [comment] 2015-03-23 14:07
?Thanks.


I tried the local import-module but nothing happened.

________________________________
Matthew Dartez, M.S.I.T. | M.S.S.E.
Systems Engineer
matteo@forzadartez.com

________________________________

**Comment by mgr32** [comment] 2015-03-23 16:52
That's interesting. One more thing - what Powershell version do you have?

**Comment by mgr32** [comment] 2015-03-23 20:51
And two more - did you run Install_to_UserModules.bat and did you try to unblock all the unzipped files? (especially PsISEProjectExplorer.dll - right click in Windows Explorer / properties / unblock)

**Comment by mgr32** [comment] 2015-04-22 18:41
Hi cajunitalian, any update on this issue?

**Comment by mgr32** [comment] 2015-09-28 07:05
Closing - unable to reproduce and no feedback. Feel free to reopen if the issue still occurs.

**Closed by mgr32** 2015-09-28 07:05 UTC
